### ISSUE TITLE
##[error]Docker run failed with exit code 1

### ISSUE THREAD

**Issue by ac0uk** [do-community/example-doctl-action#4] opened 2019-10-03 17:23 UTC
I get this error

`##[error]Docker run failed with exit code 1`

On the Save DigitalOcean kubeconfig step.. I have the DO access token set, unable to resolve, not sure what the issue is

**Comment by andrewsomething** [comment] 2019-10-03 18:32
Hi @adamcollier1. Sorry to hear you're running into issues. Was there any additional error output? Unfortunately, that's not much to go on and it is working as expected for me still.

**Comment by ac0uk** [comment] 2019-10-03 20:15
Hi @andrewsomething 

It's possible I am doing something wrong, but I can't find it if I am..

I forked the repo, then just edited workflow.yaml, added the secrets to the repo..

This is the full output

`Save DigitalOcean kubeconfig2s
##[error]Docker run failed with exit code 1
Run digitalocean/action-doctl@master
  with:
    args: kubernetes cluster kubeconfig show static-example > $GITHUB_WORKSPACE/.kubeconfig
  env:
    DIGITALOCEAN_ACCESS_TOKEN: ***
/usr/bin/docker run --name bb81cdc36ca22b824ef3918911b4ebf9e0d0_475582 --label 04bb81 --workdir /github/workspace --rm -e DIGITALOCEAN_ACCESS_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/example-doctl-action/example-doctl-action":"/github/workspace" 04bb81:cdc36ca22b824ef3918911b4ebf9e0d0 kubernetes cluster kubeconfig show static-example > $GITHUB_WORKSPACE/.kubeconfig
##[error]Docker run failed with exit code 1`

https://github.com/adamcollier1/example-doctl-action/

Maybe I am missing something I need to change.. thanks

**Comment by drevantonder** [comment] 2019-10-05 09:04
I got that error when I had the incorrect cluster name... You may have named your cluster something else on DigitaOcean.
Try run `doctl kubernetes cluster kubeconfig show static-example` on a digitalocean-authenticated terminal.

**Comment by robin-rpr** [comment] 2020-02-29 22:39
I think this issue can be closed as this can only be caused by an invalid cluster name

**Closed as completed** 2020-04-24 16:58 UTC
